packages:
  - "client"
  - "server"
  - "shared"

catalog: 
  typescript: ^5.5.4
  '@types/node': ^20.14.12
  # FiveM  
  '@citizenfx/client': 2.0.5250-1
  '@citizenfx/server': 2.0.5250-1
  #Eslint
  '@rocketseat/eslint-config': ^2.2.2
  'eslint': ^8.56.0
  'esbuild': ^0.14.10
  'esbuild-plugin-fileloc': ^0.0.6