# https://nx.dev/more-concepts/folder-structure
# https://pnpm.io/workspaces
packages:
  - "**/client/"
  - "**/server/"
  - "**/web/"
  
catalog: 
  # Bundle
  rollup: ^4.20.0
  '@rollup/plugin-commonjs': ^26.0.1
  '@rollup/plugin-node-resolve': ^15.2.3

